### ISSUE TITLE
 IndexError: index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by jian-rookie** [elias-ramzi/HAPPIER#4] opened 2023-03-18 08:08 UTC
Hello，thanks to your nice work!
I tried to reproduce the results on iNaturalist-base and SOP with a 32G V100. We ran the default commands and the model was trained in the first few epochs. However, there was a IndexError in the 20th epoch both on  iNaturalist-base and SOP.
The specific error information is as follows:
Traceback (most recent call last):
  File "happier/run.py", line 173, in run
    restore_epoch=restore_epoch,
  File "/home/yangjian/retrieval/HAPPIER-main/happier/engine/train.py", line 108, in train
    epoch=e,
  File "/home/yangjian/retrieval/HAPPIER-main/happier/lib/get_set_random_state.py", line 43, in wrapper
    output = func(*args, **kwargs)
  File "/home/yangjian/retrieval/HAPPIER-main/happier/engine/accuracy_calculator.py", line 227, in evaluate
    epoch=epoch,
  File "/home/yangjian/retrieval/HAPPIER-main/happier/engine/accuracy_calculator.py", line 144, in evaluate
    features, labels, relevances = self.get_embeddings(net, dts)
  File "/home/yangjian/retrieval/HAPPIER-main/happier/engine/accuracy_calculator.py", line 69, in get_embeddings
    self.convert_to_cuda,
  File "/home/yangjian/retrieval/HAPPIER-main/happier/engine/compute_embeddings.py", line 20, in compute_embeddings
    for i, batch in enumerate(tqdm(loader, disable=os.getenv("TQDM_DISABLE"))):
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
 data.reraise()
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yangjian/anaconda3/envs/happier/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yangjian/retrieval/HAPPIER-main/happier/datasets/base_dataset.py", line 119, in __getitem__
    relevances = self.relevances[idx, :]
IndexError: index 0 is out of bounds for dimension 0 with size 0

Could you please help us find out the possible reasons?

**Comment by elias-ramzi** [comment] 2023-03-23 08:21
Hi,

It seems that the relevances have not been computed. Have you change something in the code? 
It should have been computed automatically.
If not I will investigate why it was not the case!

**Comment by jian-rookie** [comment] 2023-03-23 11:58
I didn't change anything in the code. And the problem also happens when I reproduce the ROADMAP.

**Comment by elias-ramzi** [comment] 2023-03-27 15:16
Ok, I will try to run the code myself and will check if there are any issues. I will let you know.

Edit: After running the code it worked for me. Did you change the configuration that would make that the relevances are computed?

could you print `test_dts.relevances` in `run.py`?

**Comment by jian-rookie** [comment] 2023-03-31 02:37
Sorry for the late response. I re-run the code on SOP twice without any change. It surprisingly works. Now I can successfully reproduce this project. Thanks.

**Comment by elias-ramzi** [comment] 2023-03-31 08:36
Great to hear it works! I will close this issue as the problem seems to be fixed. Do not hesitate to re-open this or another issue if you face any problems.

**Closed as completed by elias-ramzi** 2023-03-31 08:36 UTC

**Comment by Alihan-Inc** [comment] 2024-05-14 12:19
I encountered an error while running the experiment with the following configuration:

experience.experiment_name=HAPPIER_SOP
experience.log_dir=experiments/HAPPIER
experience.seed=0
experience.max_iter=100
experience.warmup_step=5
experience.accuracy_calculator.compute_for_hierarchy_levels=[0,1]
optimizer=sop
model=resnet_ln
transform=sop
dataset=sop
loss=HAPPIER_SOP

The error occurred during the evaluation phase at the 20th epoch. I ran the experiment three times without making any changes to the code, and the error persisted.

Environment Details:

Platform: Snellius server
Torch version: 1.8.1 with CUDA 11.1
Error Message:
IndexError: index 0 is out of bounds for dimension 0 with size 0

Explanation:
The error appears to be caused by an IndexError during data loading in the DataLoader worker process. Specifically, it seems that the index 0 is out of bounds for dimension 0 with size 0 when accessing data from the dataset.

Please advise on how to resolve this issue or if any additional information is needed.

Here is the error:
[[36m2024-05-14 13:59:07,784[0m][[34mHAPPIER[0m][[32mINFO[0m] - Training : @epoch #20 for model HAPPIER_SOP[0m
[[36m2024-05-14 13:59:07,785[0m][[34mHAPPIER[0m][[32mINFO[0m] - Shuffling data[0m
[[36m2024-05-14 13:59:10,006[0m][[34mHAPPIER[0m][[32mINFO[0m] - Shuffling data[0m
[[36m2024-05-14 14:03:03,794[0m][[34mHAPPIER[0m][[32mINFO[0m] - Evaluating for epoch 20[0m
[[36m2024-05-14 14:03:03,797[0m][[34mHAPPIER[0m][[32mINFO[0m] - Getting embeddings for the test set[0m
[[36m2024-05-14 14:03:03,798[0m][[34mHAPPIER[0m][[32mINFO[0m] - Computing embeddings[0m
Error executing job with overrides: ['experience.experiment_name=HAPPIER_SOP', 'experience.log_dir=experiments/HAPPIER', 'experience.seed=0', 'experience.max_iter=100', 'experience.warmup_step=5', 'experience.accuracy_calculator.compute_for_hierarchy_levels=[0,1]', 'optimizer=sop', 'model=resnet_ln', 'transform=sop', 'dataset=sop', 'loss=HAPPIER_SOP']
Traceback (most recent call last):
  File "/home/scur2061/hyperhap/HAPPIER/happier/run.py", line 158, in run
    return eng.train(
  File "/home/scur2061/hyperhap/HAPPIER/happier/engine/train.py", line 89, in train
    metrics = evaluate(
  File "/home/scur2061/hyperhap/HAPPIER/happier/lib/get_set_random_state.py", line 43, in wrapper
    output = func(*args, **kwargs)
  File "/home/scur2061/hyperhap/HAPPIER/happier/engine/accuracy_calculator.py", line 218, in evaluate
    return acc.evaluate(
  File "/home/scur2061/hyperhap/HAPPIER/happier/engine/accuracy_calculator.py", line 138, in evaluate
    features, labels, relevances = self.get_embeddings(net, dts)
  File "/home/scur2061/hyperhap/HAPPIER/happier/engine/accuracy_calculator.py", line 60, in get_embeddings
    return compute_embeddings(
  File "/home/scur2061/hyperhap/HAPPIER/happier/engine/compute_embeddings.py", line 19, in compute_embeddings
    for i, batch in enumerate(tqdm(loader, disable=os.getenv("TQDM_DISABLE"))):
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/tqdm/std.py", line 1183, in __iter__
    for obj in iterable:
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/scur2061/.conda/envs/happier_env_111/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/scur2061/hyperhap/HAPPIER/happier/datasets/base_dataset.py", line 118, in __getitem__
    relevances = self.relevances[idx, :]
IndexError: index 0 is out of bounds for dimension 0 with size 0



In the job script, I use the following modules loads:

module load 2021 
module load cuDNN/8.2.1.32-CUDA-11.3.1                                                                     
module load 2022  
module load Anaconda3/2022.05


and this is how I created the environment:
conda create --name happier
conda activate happier
conda install python=3.9
conda install -c conda-forge cudatoolkit=11.1
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
+ the requirements.txt
